In [1]:
import tensorflow as tf
import numpy as np
sess = tf.Session()

In [2]:
def print_tensor(tensor):
    print(sess.run(tensor))

In [4]:
x = tf.constant([[3,4,5],[1,2,4]],dtype = tf.float32)
print("x")
print_tensor(x)
print("mean, var = tf.nn.moments(x,[0])")
mean, var = tf.nn.moments(x,[0])
print("Mean")
print_tensor(mean)
print("Varaiance")
print_tensor(var)
print("tf.nn.moments(x,[1])")
print_tensor(tf.nn.moments(x,[1]))
print("tf.nn.moments(x,[0,1])")
print_tensor(tf.nn.moments(x,[0,1]))

x
[[ 3.  4.  5.]
 [ 1.  2.  4.]]
mean, var = tf.nn.moments(x,[0])
Mean
[ 2.   3.   4.5]
Varaiance
[ 1.    1.    0.25]
tf.nn.moments(x,[1])
(array([ 4.        ,  2.33333325], dtype=float32), array([ 0.66666669,  1.5555557 ], dtype=float32))
tf.nn.moments(x,[0,1])
(3.1666667, 1.8055555)
