In [1]:
import tensorflow as tf
import numpy as np 

sess = tf.Session()

In [2]:
def print_tensor(tensor):
    print(sess.run(tensor))
def get_shape(tensor):
    return tensor.get_shape().as_list()

# get_shape(), print_tensor() usage

In [3]:
tensor1 = tf.constant(value = [[1, 2],[4, 8]], dtype = tf.float32)
tensor1

<tf.Tensor 'Const:0' shape=(2, 2) dtype=float32>

In [4]:
get_shape(tensor1)

[2, 2]

In [5]:
print_tensor(tensor1)

[[ 1.  2.]
 [ 4.  8.]]


# Convolution

In [6]:
def mae_conv(input2d, filter2d, padding_option = True, strides = [1,1,1,1]):
    '''
    Args
        input2d - 2d tensor
        filter2d - 2d tensor
        padding_option - boolean
            defaults to be True
            True => apply padding
            False => apply no padding
        strides - list
            defaults to be [1,1,1,1]
    '''
    in_height, in_width = get_shape(input2d)
    filter_height, filter_width = get_shape(filter2d)
    input4d = tf.reshape(input2d, [1, in_height, in_width, 1]) # batch = 1, in_channel = 1
    filter4d = tf.reshape(filter2d, [filter_height, filter_width, 1, 1]) #in_channel = 1, out_channel =1
    padding = 'SAME' if padding_option else 'VALID'
    conv = tf.nn.conv2d(input=input4d, filter = filter4d, strides = strides, padding=padding)
    batch_, conv_height, conv_width, channel_ = get_shape(conv)
    conv_r = tf.reshape(conv, [conv_height, conv_width])
    return conv_r

def mae_conv_tutorial(input2d, filter2d, padding_option = True, strides = [1,1,1,1]):
    '''
        mae_conv wrapper for tutorial 
    '''
    print("Input {}".format(get_shape(input2d)))
    print_tensor(input2d)
    print("Filter {}".format(get_shape(filter2d)))
    print_tensor(filter2d)
    print("Padding : {}".format(padding_option))
    conv = mae_conv(input2d = input2d, filter2d = filter2d, padding_option = padding_option, strides = strides)
    print("Conv_result : {}".format(get_shape(conv)))
    print_tensor(conv)

In [7]:
input1 = tf.tile(tf.constant([[1,2],[4,8]], dtype = tf.float32), [2, 2])
filter1 = tf.constant(value = [[1,0],[0,1]], dtype = tf.float32)
filter2 = tf.constant(value = [[1, 1],[0, 0]], dtype = tf.float32)

# Different filter

In [10]:
mae_conv_tutorial(input1, filter1, padding_option = False, strides = [1,1,1,1])

Input [4, 4]
[[ 1.  2.  1.  2.]
 [ 4.  8.  4.  8.]
 [ 1.  2.  1.  2.]
 [ 4.  8.  4.  8.]]
Filter [2, 2]
[[ 1.  0.]
 [ 0.  1.]]
Padding : False
Conv_result : [3, 3]
[[ 9.  6.  9.]
 [ 6.  9.  6.]
 [ 9.  6.  9.]]


In [11]:
mae_conv_tutorial(input1, filter2, padding_option = False, strides = [1,1,1,1])

Input [4, 4]
[[ 1.  2.  1.  2.]
 [ 4.  8.  4.  8.]
 [ 1.  2.  1.  2.]
 [ 4.  8.  4.  8.]]
Filter [2, 2]
[[ 1.  1.]
 [ 0.  0.]]
Padding : False
Conv_result : [3, 3]
[[  3.   3.   3.]
 [ 12.  12.  12.]
 [  3.   3.   3.]]


# Padding true or not

In [12]:
mae_conv_tutorial(input1, filter1, padding_option = True, strides = [1,1,1,1])

Input [4, 4]
[[ 1.  2.  1.  2.]
 [ 4.  8.  4.  8.]
 [ 1.  2.  1.  2.]
 [ 4.  8.  4.  8.]]
Filter [2, 2]
[[ 1.  0.]
 [ 0.  1.]]
Padding : True
Conv_result : [4, 4]
[[ 9.  6.  9.  2.]
 [ 6.  9.  6.  8.]
 [ 9.  6.  9.  2.]
 [ 4.  8.  4.  8.]]


# Different strides

In [13]:
mae_conv_tutorial(input1, filter1, padding_option = False, strides = [1, 2, 1,1])

Input [4, 4]
[[ 1.  2.  1.  2.]
 [ 4.  8.  4.  8.]
 [ 1.  2.  1.  2.]
 [ 4.  8.  4.  8.]]
Filter [2, 2]
[[ 1.  0.]
 [ 0.  1.]]
Padding : False
Conv_result : [2, 3]
[[ 9.  6.  9.]
 [ 9.  6.  9.]]


# tf.nn.conv2d(input, filter, strides, padding)
**input** : 4D tensor  
>    input_shape : [batch, in_height, in_width, **in_channels**]    

**filter** : 4D tensor  
>    output_shape : [filter_height, filter_width, **in_channels**, out_channels]  

** strides ** : 1D array with 4 elements, move the filter following directions   
>    [batch, height, width, channel] 
  
**padding** : string  
>    "SAME" - padding to make same shape with input  
>    "VALID" - no padding

## Quiz 2

When **strides** = [1,1,1,1] and **padding** = 'VALID'  
output_shape = [batch, ??, ??, out_channel]

in_height - filter_height + 1  
in_width - filter_width + 1  

In [29]:
batch = 10
height = 28
width = 28
in_channel = 1

In [30]:
x = tf.random_normal([batch, height, width, in_channel])
get_shape(x)

[10, 28, 28, 1]

In [31]:
weight1 = tf.Variable(tf.random_normal([5, 5, 1, 10]))
conv1 = tf.nn.conv2d(x, weight1, strides=[1,1,1,1],padding='VALID')
get_shape(conv1)

[10, 24, 24, 10]

In [32]:
weight2 = tf.Variable(tf.random_normal([6, 6, 10, 20]))
conv2 = tf.nn.conv2d(conv1, weight2, strides =[1,1,1,1], padding='VALID')
get_shape(conv2)

[10, 19, 19, 20]

## Quiz 3

## tf.nn.max_pool(value, ksize, strides, padding)
* value : 4D tensor   
> [batch, height, width, channels]
* ksize : list with 4 elements  
> the size of the window in the shape of value
* strides : list with 4 elements  
> the stride of the sliding window in the shape of value
* padding : string  
> **VALID** : No padding
> **SAME** : padding

In [54]:
x = tf.random_normal([4, 8, 11, 6])
get_shape(x)

[4, 8, 11, 6]

In [55]:
pool1 = tf.nn.max_pool(value=x, ksize=[10000, 3, 4, 2], strides=[1000, 4, 6, 3], padding= 'VALID')
get_shape(pool1)

[4, 2, 2, 2]

In [56]:
x = tf.random_normal([30, 28, 28, 1])
get_shape(x)

[30, 28, 28, 1]

In [59]:
weight1 = tf.Variable(tf.random_normal([5,5,1,10]))
conv1 = tf.nn.conv2d(x, weight1, [1,1,1,1], 'VALID')
get_shape(conv1)

[30, 24, 24, 10]

In [61]:
pool1 = tf.nn.max_pool(conv1, [1,2,2,1], [1,4,4,1], 'VALID')
get_shape(pool1)

[30, 6, 6, 10]

In [62]:
weight2 = tf.Variable(tf.random_normal([3,3,10,20]))
conv2 = tf.nn.conv2d(pool1, weight2,[1,1,1,1], 'VALID')
get_shape(conv2)

[30, 4, 4, 20]

In [63]:
pool2 = tf.nn.max_pool(conv2, [1,2,2,1], [1,2,2,1], 'VALID')
get_shape(pool2)

[30, 2, 2, 20]

## Quiz4

# More on channel and batch

In [14]:
input1 = tf.constant([[1, 2],[4, 8]], dtype = tf.float32)
input2 = tf.constant([[16, 32],[64, 128]], dtype = tf.float32)
input3 = tf.constant([[256, 512], [64, 128]], dtype = tf.float32)

In [15]:
batch_stack = tf.stack(values = [input1, input2,input3], axis = 0)
batch_stack

<tf.Tensor 'stack:0' shape=(3, 2, 2) dtype=float32>

In [16]:
print_tensor(batch_stack)

[[[   1.    2.]
  [   4.    8.]]

 [[  16.   32.]
  [  64.  128.]]

 [[ 256.  512.]
  [  64.  128.]]]


In [17]:
batch_stack_expand = tf.expand_dims (batch_stack, dim=-1)
batch_stack_expand

<tf.Tensor 'ExpandDims:0' shape=(3, 2, 2, 1) dtype=float32>

In [18]:
channel_stack = tf.stack(values =[input1, input2, input3], axis = 2)
channel_stack_expand = tf.expand_dims(channel_stack, dim = 0)
channel_stack_expand

<tf.Tensor 'ExpandDims_1:0' shape=(1, 2, 2, 3) dtype=float32>

In [19]:
batch_filter = tf.constant(value = 1, shape = [2, 2, 1, 1], dtype = tf.float32)
channel_filter = tf.constant(value = 1, shape = [2, 2, 3, 1], dtype = tf.float32)

In [22]:
conv_batch = tf.nn.conv2d(batch_stack_expand, batch_filter, strides = [1,1,1,1], padding='VALID')

In [23]:
print_tensor(conv_batch)

[[[[  15.]]]


 [[[ 240.]]]


 [[[ 960.]]]]


In [24]:
get_shape(conv_batch)

[3, 1, 1, 1]

In [25]:
conv_channel = tf.nn.conv2d(channel_stack_expand, channel_filter, strides = [1,1,1,1], padding='VALID')

In [26]:
print_tensor(conv_channel)

[[[[ 1215.]]]]
