In [1]:
import tensorflow as tf
sess = tf.Session()
def print_tensor(x):
    print(sess.run(x))

# tf.nn.dropout(x, keep_prob, noise_shape)
* **x** : input
* **keep_prob** : (0,1]
* **noise_shape** : 
> default to be shape(x)  
> if $noise shape[i] == get shape(x)[i]$
=> independent decision  
> ex) $shape(x) = [k, l, m, n], [k, 1, 1, n]$
dim 1, 2 is determined togther
dim 0, 3 is determined independently

In [2]:
x = tf.constant([1., 2., 4., 6.])
print("x")
print_tensor(x)
print("tf.nn.dropout(x, keep_prob = 0.25)")
print_tensor(tf.nn.dropout(x, keep_prob=0.25))
print_tensor(tf.nn.dropout(x, keep_prob=0.25))
print_tensor(tf.nn.dropout(x, keep_prob=0.25))

x
[ 1.  2.  4.  6.]
tf.nn.dropout(x, keep_prob = 0.25)
[ 0.  8.  0.  0.]
[  0.   0.  16.  24.]
[  0.   8.  16.   0.]


In [3]:
x = tf.constant([[[1.,2.,3.],[4.,5.,6.]],[[7.,8.,9.],[10.,11.,12.]]])
print("x : {}".format(x.get_shape()))
print_tensor(x)
print("tf.nn.dropout(x, keep_prob=0.5, noise_shape=[1, 2, 3])")
print_tensor(tf.nn.dropout(x, keep_prob=0.5, noise_shape=[1, 2, 3]))
print_tensor(tf.nn.dropout(x, keep_prob=0.5, noise_shape=[1, 2, 3]))
print_tensor(tf.nn.dropout(x, keep_prob=0.5, noise_shape=[1, 2, 3]))
print_tensor(tf.nn.dropout(x, keep_prob=0.5, noise_shape=[1, 2, 3]))
print("tf.nn.dropout(x, keep_prob=0.5, noise_shape=[2, 1, 3])")
print_tensor(tf.nn.dropout(x, keep_prob=0.5, noise_shape=[2, 1, 3]))
print_tensor(tf.nn.dropout(x, keep_prob=0.5, noise_shape=[2, 1, 3]))
print_tensor(tf.nn.dropout(x, keep_prob=0.5, noise_shape=[2, 1, 3]))
print_tensor(tf.nn.dropout(x, keep_prob=0.5, noise_shape=[2, 2, 3]))
print("tf.nn.dropout(x, keep_prob=0.5, noise_shape=[2, 2, 1])")
print_tensor(tf.nn.dropout(x, keep_prob=0.5, noise_shape=[2, 2, 1]))
print_tensor(tf.nn.dropout(x, keep_prob=0.5, noise_shape=[2, 2, 1]))
print_tensor(tf.nn.dropout(x, keep_prob=0.5, noise_shape=[2, 2, 1]))
print_tensor(tf.nn.dropout(x, keep_prob=0.5, noise_shape=[2, 2, 1]))

x : (2, 2, 3)
[[[  1.   2.   3.]
  [  4.   5.   6.]]

 [[  7.   8.   9.]
  [ 10.  11.  12.]]]
tf.nn.dropout(x, keep_prob=0.5, noise_shape=[1, 2, 3])
[[[  0.   0.   0.]
  [  0.   0.  12.]]

 [[  0.   0.   0.]
  [  0.   0.  24.]]]
[[[  0.   4.   6.]
  [  0.   0.   0.]]

 [[  0.  16.  18.]
  [  0.   0.   0.]]]
[[[  2.   4.   6.]
  [  0.   0.   0.]]

 [[ 14.  16.  18.]
  [  0.   0.   0.]]]
[[[  2.   0.   0.]
  [  0.   0.   0.]]

 [[ 14.   0.   0.]
  [  0.   0.   0.]]]
tf.nn.dropout(x, keep_prob=0.5, noise_shape=[2, 1, 3])
[[[  0.   4.   6.]
  [  0.  10.  12.]]

 [[  0.  16.   0.]
  [  0.  22.   0.]]]
[[[  2.   4.   6.]
  [  8.  10.  12.]]

 [[ 14.   0.   0.]
  [ 20.   0.   0.]]]
[[[  0.   0.   0.]
  [  0.   0.   0.]]

 [[  0.   0.  18.]
  [  0.   0.  24.]]]
[[[  0.   4.   6.]
  [  0.  10.   0.]]

 [[  0.  16.  18.]
  [ 20.   0.  24.]]]
tf.nn.dropout(x, keep_prob=0.5, noise_shape=[2, 2, 1])
[[[ 2.  4.  6.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]]]
[[[  0.   0.   0.]
  [  0.   0.  